### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by macizo-hook** [macizo-hook/discord-blaine-bot#1]
Error handling in the bot could be improved.

**Comment by amirmohammadre** [comment]
Hi @macizo-hook  
I think that in the `award_role` function, it is better to place the `if...elif...else` commands in the `try` block.
may I work on this?

**Comment by macizo-hook** [comment]
Yes, thanks @amirmohammadre!

**Comment by amirmohammadre** [comment]
Dear @macizo-hook , thanks for the opportunity.

**Comment by amirmohammadre** [comment]
Dear @macizo-hook , I've sent a PR for this.

**Comment by macizo-hook** [comment]
Nicely done! I will review it today.
